/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xahocwssdmfmonuupegu"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhaG9jd3NzZG1mbW9udXVwZWd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY2NTAxNzYsImV4cCI6MjA5MjIyNjE3Nn0.anOHfZ--abvurJMWcl9pu6SUsVplzgyNUQZSMYK2mIg"